<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catevento | Login</title>
    <link rel="stylesheet" href="css/cadastro.css">
    <link rel="stylesheet" href="css/animacoes.css">
    <link rel="stylesheet" href="css/media-query.css">
    <link rel="stylesheet" href="css/login.css">
    <link rel="shortcut icon" href="imagens/logo.png" type="image/png">
    <script src="https://kit.fontawesome.com/05ac79b2f0.js" crossorigin="anonymous"></script>
</head>
<body>
    <main id="main">
        <article id="article-login">
            <a href="#"><img src="imagens/logo.png" alt="logo catevento" id="logo" title="Voltar para a página principal."></a>
            <h1 class="login-title">Página em desenvolvimento</h1>
            <p id="login-paragrafo">Estamos trabalhando para tornar essa pagina acessível :)</p>
            <a href="Cadastro.php" id="btn-login">Voltar</a>
        </article>
        <article id="article-vetor">
            <img src="imagens/dev-ilustracao.png" alt="ilustração de um site em desenvolvimento" id="ilustracao-web">
        </article>
    </main>
    <script src="js/dark-mode.js"></script>
</body>